name: "Performance Comparison (Criterion)"
description: "Compares PR performance against base with Criterion"
author: "chipbuster"
inputs:
  token:
    description: "GitHub Token which provides comment access to the repo"
    required: true
    default: ""
  workDir:
    description: "Sets the directory to run the benchmarks, relative to the project directory"
    required: false
    default: "./"
  cargoBenchName:
    description: "The benchmark name to run."
    required: false
    default: ""
  gitBranchName:
    description: "Branch to compare PR against"
    required: false
    default: "master"
  doFetch:
    description: "Run `git fetch` before performing other actions"
    required: false
    default: true
  doClean:
    description: "Run `cargo clean` before starting benchmarks"
    required: false
    default: true
runs:
  using: 'node16'
  main: 'dist/index.js'
